DROP TABLE reviews;DROP TABLE users;DROP TABLE books;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR UNIQUE NOT NULL,
	password VARCHAR NOT NULL
);

CREATE TABLE books (
	id SERIAL PRIMARY KEY,
	isbn VARCHAR UNIQUE NOT NULL,
	title VARCHAR NOT NULL,
	author VARCHAR NOT NULL,
	year INTEGER NOT NULL
);

CREATE TABLE reviews (
	id SERIAL PRIMARY KEY,
	book_id INTEGER NOT NULL REFERENCES books,
	user_id INTEGER NOT NULL REFERENCES users,
	rating INTEGER NOT NULL,
	message VARCHAR
);